# how the basic.json file look in .yml format
# Unlike .json file .yml file provides comment and multiline strings

myapp:
  services: CI_CD_project # for strings we can use quotes or without quotes
  test1: script1
  test2: script2
  simple_array: [1, 2, 3, 4, 5]
  arr_of_objects:
    - key1: value1
      random1: randomvalue1
    - key2: value2
      random2: randomvalue2
  multiline_string: | # use pipe "|" symbol
    hello there
    I am Dhiraj
    I am BIT Student


# steps to write your github action

# step 1: first thing you want to write in your github action is name use "name" key

name: My first github action

# step 2: second thing you want to write when these action should run. use "on" key. What the
#         trigger is? Here it is "push".  

on: 
  push:
    branches:
      - secondary

# step 3: state the set of tasks/jobs you want to in this action when the (above example: push) 
#         is triggered

jobs:
# github executes these jobs in parallel since there are objects (print-hello-world & print-hello-world2)
# not list
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "hello world"
      - name: Print Step 2
        run: echo "this is step 2"
  print-hello-world2:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world2
        run: echo "hello world2"
      - name: print step2
        run: echo "step 2"

"""
For GitHub Actions to execute, the .yml workflow files must be placed in 
the .github/workflows directory at the root level of your repository. 
This specific directory structure is required by GitHub to recognize and run the workflow files.

""" 














